---
name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
      - 'gh-pages'
  workflow_dispatch:

jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - runtime_identifier: win-x86
          - runtime_identifier: win-x64
          - runtime_identifier: linux-x64
          - runtime_identifier: linux-musl-x64
          - runtime_identifier: linux-arm
          - runtime_identifier: linux-arm64
          - runtime_identifier: osx-x64
          - runtime_identifier: osx.11.0-arm64
          - runtime_identifier: osx.12-arm64
    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Print environment
        run: |
          dotnet --info
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Restore/Clean service
        run: |
          echo "Restore"
          dotnet restore
          echo "Clean"
          dotnet clean -c "Release"

      - name: Build Splunk App
        env:
          BIN_OUT: app/bitwarden_event_logs/bin
          LIB_OUT: app/bitwarden_event_logs/lib/Bitwarden_Splunk
          RUNTIME_IDENTIFIER: ${{ matrix.runtime_identifier }}
        run: |
          # Create directories
          mkdir -p ${BIN_OUT}
          mkdir -p ${LIB_OUT}

          cp -R src/Splunk/* ${LIB_OUT}
          dotnet publish -c Release -o "${BIN_OUT}" -r "${RUNTIME_IDENTIFIER}"

      - name: TEST STEP
        run: |
          ls -alh app/bitwarden_event_logs
          echo "**********"
          ls -alh app/bitwarden_event_logs/bin
          echo "**********"
          ls -alh app/bitwarden_event_logs/lib/Bitwarden_Splunk
          echo "**********"
          exit 1

      - name: Publish service
        shell: pwsh
        run: |
          ./build.ps1 -task app -os win
          ./build.ps1 -task app -os lin
          ./build.ps1 -task app -os mac

      - name: Upload artifacts (win-x64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_win-x64
          path: build/app/win-x64
          if-no-files-found: error

      - name: Upload artifacts (win-x86)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_win-x86
          path: build/app/win-x86
          if-no-files-found: error

      - name: Upload artifacts (linux-x64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_linux-x64
          path: build/app/linux-x64
          if-no-files-found: error

      - name: Upload artifacts (linux-musl-x64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_linux-musl-x64
          path: build/app/linux-musl-x64
          if-no-files-found: error

      - name: Upload artifacts (linux-arm64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_linux-arm64
          path: build/app/linux-arm64
          if-no-files-found: error

      - name: Upload artifacts (linux-arm)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_linux-arm
          path: build/app/linux-arm
          if-no-files-found: error

      - name: Upload artifacts (osx-x64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_osx-x64
          path: build/app/osx-x64
          if-no-files-found: error

      - name: Upload artifacts (osx.12-arm64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_osx.12-arm64
          path: build/app/osx.12-arm64
          if-no-files-found: error

      - name: Upload artifacts (osx.11.0-arm64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_osx.11.0-arm64
          path: build/app/osx.11.0-arm64
          if-no-files-found: error
